name: Build

env:
  XCODE_VERSION: "16.3"

on:
  push:
    tags:
      - "v*"
    branches:
      - "*"
  pull_request:

jobs:
  lint:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5

      # Setup environment
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Print swift version
        run: swift --version

      # Install linters
      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Install periphery
        run: |
          brew install periphery

      # Run linters
      - name: Run linters
        run: |
          make lint

  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5

      # Setup environment
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Print swift version
        run: swift --version

      # Run tests
      - name: Run tests
        run: |
          make test

  build:
    needs:
      - lint
      - test
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5

      # Setup environment
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Get swift version
        run: swift --version

      - run: make build

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: See [CHANGELOG.md](./CHANGELOG.md) for the list of changes.
          draft: false
          prerelease: false
